### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by danvega** [u12206050/gridsome-plugin-algolia#2]
I have a `.evn.development` with the following variables defined 

```
ALGOLIA_APP_ID=123456789
ALGOLIA_API_KEY=123456789
ALGOLIA_INDEX_NAME=blog_posts
```

I know your instructions have an example where you require dotenv but it's already built into Gridsome. If you look at the docs it says that we should be able to use these values in our configuration https://gridsome.org/docs/environment-variables 

When I use the actual values everything works fine but when I try to use the environment variables like so

```
    {
      use: `gridsome-plugin-algolia`,
      options: {
        appId: process.env.ALGOLIA_APP_ID,
        apiKey: process.env.ALGOLIA_API_KEY,
        collections,
        chunkSize: 10000, // default: 1000
        enablePartialUpdates: false, // default: false
      },
    },
```

I get the following error: 

```
AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
    at AlgoliaSearchNodeJS.AlgoliaSearchCore (/Users/vega/dev/gridsome/danvega-dev/node_modules/algoliasearch/src/AlgoliaSearchCore.js:50:11)
    at AlgoliaSearchNodeJS.AlgoliaSearch (/Users/vega/dev/gridsome/danvega-dev/node_modules/algoliasearch/src/AlgoliaSearch.js:11:21)
    at AlgoliaSearchNodeJS.AlgoliaSearchServer (/Users/vega/dev/gridsome/danvega-dev/node_modules/algoliasearch/src/server/builds/AlgoliaSearchServer.js:17:17)
    at new AlgoliaSearchNodeJS (/Users/vega/dev/gridsome/danvega-dev/node_modules/algoliasearch/src/server/builds/node.js:79:23)
    at algoliasearch (/Users/vega/dev/gridsome/danvega-dev/node_modules/algoliasearch/src/server/builds/node.js:68:10)
    at afterBuild (/Users/vega/dev/gridsome/danvega-dev/node_modules/gridsome-plugin-algolia/index.js:58:20)
    at Promise.all.events.(anonymous function).map (/Users/vega/dev/gridsome/danvega-dev/node_modules/gridsome/lib/app/App.js:144:41)
    at Array.map (<anonymous>)
    at App.dispatch (/Users/vega/dev/gridsome/danvega-dev/node_modules/gridsome/lib/app/App.js:143:47)
    at module.exports (/Users/vega/dev/gridsome/danvega-dev/node_modules/gridsome/lib/build.js:53:13)
```

This only happens on the build so these values should be injected. Any idea why this wouldn't work? I got a basic search working but until I can extract these values to env variables I can't push this code. Thanks again for the plugin!

**Comment by u12206050** [comment]
@danvega For builds you need to have a `.env.production` file instead of the `.env.development` file. 

Thanks for the hint about the dotenv.

**Comment by danvega** [comment]
So I just put a .env file in my root and that worked fine. So I will add that to my root and then put that in the .gitignore. I have the variables in Netlify so I won't need a production version of that. Thanks for all the help! I am going to close this.
