### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by kayakmind** [u12206050/gridsome-plugin-algolia#3]
Thanks for putting this together. When I run buildin gridsome, I'm getting this error:

Error: Algolia failed: report is not defined
    at afterBuild (/Users/chrisemery/Sites/tbs-gridsome-2019/node_modules/gridsome-plugin-algolia/index.js:174:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Any suggestions you might have to fix it would be greatly appreciated. Thanks.

**Comment by kayakmind** [comment]
Actually, I think I just got it to work. Looks like i needed to drop the fields that weren't in my schema from the query. I did notice one typo on the gridsome site. I think there is a missing comma after: transformer: ({ data }) => data.allBlogPost.edges.map(({ node }) => node)
Throws an error about the next line of code.
